version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'